import { PROCESS_STATES } from 'ethpkg'

export const PROCESS_EVENTS = {

  ...PROCESS_STATES,

  CLIENT_INIT_STARTED: 'CLIENT_INIT_STARTED',

  CLIENT_START_STARTED: 'CLIENT_START_STARTED',
  CLIENT_START_FINISHED: 'CLIENT_START_FINISHED',

  // the client manager is loading the release / version list from a remote repo 
  RESOLVE_RELEASE_STARTED: 'RESOLVE_RELEASE_STARTED',
  RESOLVE_RELEASE_FINISHED: 'RESOLVE_RELEASE_FINISHED',

  RESOLVE_BINARY_STARTED: 'RESOLVE_BINARY_STARTED',
  RESOLVE_BINARY_FINISHED: 'RESOLVE_BINARY_FINISHED',

  // 
  VERIFICATION_ERROR: 'VERIFICATION_ERROR',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  PACKAGE_WRITTEN: 'PACKAGE_WRITTEN',
  BINARY_EXTRACTION_STARTED: 'BINARY_EXTRACTION_STARTED',
  BINARY_EXTRACTION_PROGRESS: 'BINARY_EXTRACTION_PROGRESS',
  BINARY_EXTRACTION_FINISHED: 'BINARY_EXTRACTION_FINISHED',

  RESOLVE_DEPENDENCIES_STARTED: 'RESOLVE_DEPENDENCIES_STARTED',
  RESOLVE_DEPENDENCIES_FINISHED: 'RESOLVE_DEPENDENCIES_FINISHED',

  DOCKERFILE_FOUND: 'DOCKERFILE_FOUND',

  CREATE_DOCKER_IMAGE_FROM_FILE_STARTED: 'CREATE_DOCKER_IMAGE_FROM_FILE_STARTED',
  CREATE_DOCKER_IMAGE_FROM_FILE_FINISHED: 'CREATE_DOCKER_IMAGE_FROM_FILE_FINISHED',

  FIND_EXISTING_DOCKER_CONTAINER_STARTED: 'FIND_EXISTING_DOCKER_CONTAINER_STARTED',
  FIND_EXISTING_DOCKER_CONTAINER_FINISHED: 'FIND_EXISTING_DOCKER_CONTAINER_FINISHED',

  CREATE_DOCKER_CONTAINER_STARTED: 'CREATE_DOCKER_CONTAINER_STARTED',
  CREATE_DOCKER_CONTAINER_FINISHED: 'CREATE_DOCKER_CONTAINER_FINISHED',

  PULL_DOCKER_IMAGE_STARTED: 'PULL_DOCKER_IMAGE_STARTED',
  PULL_DOCKER_IMAGE_PROGRESS: 'PULL_DOCKER_IMAGE_PROGRESS',
  PULL_DOCKER_IMAGE_FINISHED: 'PULL_DOCKER_IMAGE_FINISHED',


  DOCKER_CLIENT_READY: 'DOCKER_CLIENT_READY',

  // raw docker events during setup of images & containers
  DOCKER_EVENT: 'DOCKER_EVENT',

}